server {
    listen 80;

    server_name api.appfollowup.com;

    client_max_body_size 8M;

    location / {
        proxy_pass http://ai:8000/;
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
        proxy_buffers 8 32k;
        proxy_buffer_size 64k;

        error_log /var/log/webservice.log;
    }
}

server {
    listen 443 ssl;

    server_name api.appfollowup.com;

    ssl_certificate /etc/nginx/certs/appfollowup.pem;
    ssl_certificate_key /etc/nginx/certs/appfollowup.key;

    client_max_body_size 8M;

    location / {
        proxy_pass http://ai:8000/;
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
        proxy_buffers 8 32k;
        proxy_buffer_size 64k;

        error_log /var/log/webservice.log;
    }
}