"""change method forecast

Revision ID: 044b40826ae7
Revises: 8e937f6abc52
Create Date: 2026-04-03 00:43:52.556043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '044b40826ae7'
down_revision: Union[str, Sequence[str], None] = '8e937f6abc52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecast_point_evaluations', sa.Column('target_price', sa.Float(), nullable=False))
    op.add_column('forecast_point_evaluations', sa.Column('lower_bound_price', sa.Float(), nullable=False))
    op.add_column('forecast_point_evaluations', sa.Column('upper_bound_price', sa.Float(), nullable=False))
    op.add_column('forecast_point_evaluations', sa.Column('within_forecast_range', sa.Boolean(), nullable=False))
    op.add_column('forecast_point_evaluations', sa.Column('range_deviation_percent', sa.Float(), nullable=False))
    op.drop_column('forecast_point_evaluations', 'within_tolerance')
    op.drop_column('forecast_point_evaluations', 'estimated_price')
    op.add_column('forecast_points', sa.Column('target_price', sa.Float(), nullable=False))
    op.add_column('forecast_points', sa.Column('lower_bound_price', sa.Float(), nullable=False))
    op.add_column('forecast_points', sa.Column('upper_bound_price', sa.Float(), nullable=False))
    op.drop_column('forecast_points', 'estimated_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecast_points', sa.Column('estimated_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('forecast_points', 'upper_bound_price')
    op.drop_column('forecast_points', 'lower_bound_price')
    op.drop_column('forecast_points', 'target_price')
    op.add_column('forecast_point_evaluations', sa.Column('estimated_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('forecast_point_evaluations', sa.Column('within_tolerance', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('forecast_point_evaluations', 'range_deviation_percent')
    op.drop_column('forecast_point_evaluations', 'within_forecast_range')
    op.drop_column('forecast_point_evaluations', 'upper_bound_price')
    op.drop_column('forecast_point_evaluations', 'lower_bound_price')
    op.drop_column('forecast_point_evaluations', 'target_price')
    # ### end Alembic commands ###
