"""analisys tables forecast

Revision ID: 07e0ab829419
Revises: 5affc8200aba
Create Date: 2026-03-10 01:43:55.675554

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "07e0ab829419"
down_revision: Union[str, Sequence[str], None] = "5affc8200aba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "forecast_point_evaluations",
        sa.Column(
            "forecast_point_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
        sa.Column(
            "forecast_asset_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
        sa.Column("reference_price", sa.Float(), nullable=True),
        sa.Column("estimated_price", sa.Float(), nullable=False),
        sa.Column("actual_price", sa.Float(), nullable=False),
        sa.Column("absolute_error", sa.Float(), nullable=False),
        sa.Column("percentage_error", sa.Float(), nullable=False),
        sa.Column("predicted_direction", sa.String(length=20), nullable=False),
        sa.Column("actual_direction", sa.String(length=20), nullable=False),
        sa.Column("direction_correct", sa.Boolean(), nullable=False),
        sa.Column("within_tolerance", sa.Boolean(), nullable=False),
        sa.Column("tolerance_percent", sa.Float(), nullable=False),
        sa.Column("evaluation_status", sa.String(length=30), nullable=False),
        sa.Column(
            "id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["forecast_asset_id"],
            ["forecast_assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["forecast_point_id"],
            ["forecast_points.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("forecast_point_id"),
    )
    op.create_table(
        "forecast_point_outcomes",
        sa.Column(
            "forecast_point_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
        sa.Column("actual_datetime", sa.DateTime(), nullable=False),
        sa.Column("actual_price", sa.Float(), nullable=False),
        sa.Column("price_source", sa.String(length=50), nullable=True),
        sa.Column(
            "id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["forecast_point_id"],
            ["forecast_points.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("forecast_point_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("forecast_point_outcomes")
    op.drop_table("forecast_point_evaluations")
    # ### end Alembic commands ###
