"""ai tables analisys

Revision ID: 8e937f6abc52
Revises: 99f0cdc0802a
Create Date: 2026-03-31 01:21:18.877023

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision: str = "8e937f6abc52"
down_revision: Union[str, Sequence[str], None] = "99f0cdc0802a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("symbol", sa.String(length=30), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column(
            "id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_assets",
        sa.Column(
            "user_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
        sa.Column(
            "asset_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
        sa.Column(
            "id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "forecast_ai_reports",
        sa.Column(
            "forecast_request_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
        sa.Column(
            "forecast_asset_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
        sa.Column(
            "diagnostic_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
        sa.Column("analysis_summary", sa.String(length=1000), nullable=False),
        sa.Column("technical_explanation", sa.String(length=2000), nullable=True),
        sa.Column("business_explanation", sa.String(length=2000), nullable=True),
        sa.Column("risk_level", sa.String(length=20), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=True),
        sa.Column("recommended_actions", sa.JSON(), nullable=True),
        sa.Column("code_review_targets", sa.JSON(), nullable=True),
        sa.Column("experiment_suggestions", sa.JSON(), nullable=True),
        sa.Column("llm_raw_response", sa.JSON(), nullable=True),
        sa.Column(
            "id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["diagnostic_id"],
            ["forecast_diagnostics.id"],
        ),
        sa.ForeignKeyConstraint(
            ["forecast_asset_id"],
            ["forecast_assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["forecast_request_id"],
            ["forecast_requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("diagnostic_id"),
        sa.UniqueConstraint("forecast_asset_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("forecast_ai_reports")
    op.drop_table("user_assets")
    op.drop_table("assets")
    # ### end Alembic commands ###
