from typing import List, Protocol
from uuid import UUID
from app.models.investiment import Investiment
from app.schemas.investiment_schema import InvestimentIn, InvestimentOut


class IInvestimentRepository(Protocol):
    def create(self, investiment_data: InvestimentIn) -> InvestimentOut: ...
    def find_by_id(self, id: UUID) -> InvestimentOut: ...
    def find_by_user(self, user_id: UUID) -> List[InvestimentOut]: ...
    def find_by_active(self, user_id: UUID) -> List[InvestimentOut]: ...
    def update(self, investiment: Investiment, investiment_data: InvestimentIn) -> InvestimentOut: ...
