from typing import List, Protocol
from uuid import UUID
from app.constants.enums.type_active_enum import TypeActiveEnum
from app.schemas.active_schema import ActiveIn, ActiveOut


class IActiveRepository(Protocol):
    def create(self, active_data: ActiveIn) -> ActiveOut: ...
    def find_all(self) -> List[ActiveOut]: ...
    def find_by_id(self, id: UUID) -> ActiveOut: ...
    def find_by_ticker(self, ticker: str, type: TypeActiveEnum) -> ActiveOut: ...
