from typing import List, Protocol
from uuid import UUID
from app.models.alert import Alert
from app.schemas.alert_schema import AlertIn, AlertOut



class IAlertRepository(Protocol):
    def create(self, alert_data: AlertIn) -> AlertOut: ...
    def find_by_id(self, id: UUID) -> AlertOut: ...
    def find_by_user(self, user_id: UUID) -> List[AlertOut]: ...
    def find_by_active(self, user_id: UUID) -> List[AlertOut]: ...
    def update(self, alert: Alert, alert_data: AlertIn) -> AlertOut: ...