from typing import List, Protocol
from uuid import UUID
from app.models.plan import Plan
from app.schemas.plan_schema import PlanIn, PlanOut


class IPlanRepository(Protocol):
    def create(self, plan_in: PlanIn) -> PlanOut: ...
    def find_by_id(self, id: UUID) -> PlanOut: ...
    def find_all(self) -> List[PlanOut]: ...
    def update(self, plan: Plan, plan_in: PlanIn) -> PlanOut: ...
    def delete(self, plan: Plan) -> bool: ...
