from typing import List, Protocol
from uuid import UUID
from app.models.subscription import Subscription
from app.schemas.subscription_schema import SubscriptionIn, SubscriptionOut


class ISubscriptionRepository(Protocol):
    def create(self, subscription_in: SubscriptionIn) -> SubscriptionOut: ...
    def find_by_id(self, id: UUID) -> SubscriptionOut: ...
    def find_all(self) -> List[SubscriptionOut]: ...
    def update(
        self, subscripition: Subscription, subscription_in: SubscriptionIn
    ) -> SubscriptionOut: ...
    def delete(self, subscripition: Subscription) -> bool: ...
