from typing import List, Protocol
from uuid import UUID
from app.models.user import User
from app.schemas.user_asset_schema import UserAssetOut
from app.schemas.user_schema import UserIn, UserOut


class IUserRepository(Protocol):
    def create(self, user_in: UserIn, key: str) -> UserOut: ...
    def find_by_id(self, id: UUID) -> UserOut: ...
    def register_password(self, user: User, password: str) -> UserOut: ...
    def find_by_email(self, email: str) -> UserOut: ...
    def find_all(self) -> List[UserOut]: ...
    def update(self, user: User, user_in: UserIn) -> UserOut: ...
    def delete(self, user: User) -> bool: ...
